apiVersion: "apiextensions.k8s.io/v1"
kind: "CustomResourceDefinition"
metadata:
  name: "users.ir0.cn"
spec:
  group: "ir0.cn"
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["name"]
              properties:
                name:
                  type: "string"
                  description: "User Name"
  scope: "Namespaced"
  names:
    plural: "users"
    singular: "user"
    kind: "User"
    listKind: "UserList"